events { worker_connections 1024; }

http {
    server {
        listen 8080;


        location /api/notifications {
            proxy_pass http://notifications-svc-s05:8151/api/notifications;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location /api/devices {
            proxy_pass http://devices-svc:8266/api/devices;
            proxy_set_header Host $host;
        }
    }
}