name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main

jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f notifications_svc/requirements.txt ]; then pip install -r notifications_svc/requirements.txt; fi

      - name: Run Linter (Flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Verify Docker Compose Configuration
        run: |
          docker compose config


      - name: Build Notifications Service Docker Image
        run: |
          docker build -t notifications-svc-s05:latest ./notifications_svc

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Validate Kubernetes Manifests (CD Dry-Run)
        run: |
          kubectl apply --filename=k8s/deployment.yaml --dry-run=client
          echo "=== ПРОЦЕСС CD УСПЕШЕН: Манифесты валидны и готовы к раскатке на кластер! ==="